### ISSUE TITLE
[BUG] Concurrent Requests Share Input Data

### ISSUE THREAD

**Issue by theMomax** [khanlou/Meridian#8]
The `@ParameterStorage` used e.g. in `@QueryParameter` is shared among all instances of one implementation of `Responder`.

Consider the following code:

```swift
import Meridian
import Foundation

struct SampleEndpoint: Responder {
    @QueryParameter("name") var name: String
    
    
    func execute() throws -> Response {
        let n = name
        print(n)
        sleep(5)
        print("\(n) \(n == name ? "==" : "!=") \(name)")
        return JSON(name)
    }
}

Server(errorRenderer: BasicErrorRenderer())
    .register {
        SampleEndpoint()
            .on("/")
    }
    .listen()
```

When two request arrive within the 5 second margin the `name` of the second one overrides the `name` in the first request. E.g.:
```bash
echo "http://localhost:3000/?name=khanlou\nhttp://localhost:3000/?name=themomax" | xargs -P 2 -n 1 curl
"themomax""themomax"
```

While my example is blocking, I think this problem should prevail for non-blocking `Responder`s since there are multiple `EventLoop`s running anyways.

We had the exact same issue for [Apodini](https://github.com/Apodini/Apodini/issues/11). We were able to solve it by using the [Runtime](https://github.com/wickwirew/Runtime) framework instead of `Mirror`. Runtime allows for editing value types and thus don't have to use a `class` based store on the parameter types. 

Please let me know in case you find a solution that doesn't require Runtime.

**Comment by khanlou** [comment]
Hmm, good find! I wonder if we can use `isKnownUniquelyReferenced` to make it effectively copy-on-write? Did yall try that?

**Comment by theMomax** [comment]
No, we didn’t. Never heard about it before tbh. I’m curious to see how it turns out.

**Comment by khanlou** [comment]
`isKnownUniquelyReferenced` didn't work, because `update(_ requestContext: RequestContext, errors: inout [Error])` isn't mutating. And if it could be mutating, then we wouldn't need parameter storage in the first place. I will think more about this

**Comment by theMomax** [comment]
I may have found another solution next to the Runtime framework that is based on `Codable`. I haven't implemented it yet, but I am pretty confident it works. The basic idea is that instead of relying on runtime reflection we abuse the automatic conformance to `Codable` in order to get references to all children of a `Responder`. We have to implement a custom class that is both an `Encoder` and `Decoder` and basically just stores all the property wrappers used on a `Responder` while encoding. Each time a request comes in, we generate new `Responder` instance by decoding from this same custom class instance.
The point is that we don't pass out the original property wrapper objects in the process of decoding. At this point we can perform mutating operations on the property wrapper instances. Here you'd have to allocate a new `@ParameterStorage` on a copy of the original property wrapper and pass out this copy.

~~As I already mentioned, I haven't tried this out yet. I don't know how this approach would compare to the usage of the Runtime library in regards to runtime-performance. Based on the runtime of the `JSONDecoder`, I could imagine this approach could be up to 3x more performant as compared to the Runtime library, but that is just a semi-educated guess.~~

Edit: You can find a gist with a sample implementation and benchmarks [here](https://gist.github.com/theMomax/7c9621c3b775923f90f50893a43fc32d).

**Comment by mxcl** [comment]
Or you could instantiate `Responder` when the route is hit rather than keeping a single instance around for the application’s lifetime.

**Comment by khanlou** [comment]
....That actually gives me an idea. What if we stored the RouteBuilder block and just ran it again to construct new structs (and more importantly new backing stores) any time a new request came in?

**Comment by khanlou** [comment]
That fix seems to solve the problem! I'm going to try it out for a few weeks in some personal projects before making a release, but this is really promising!

**Comment by theMomax** [comment]
I‘m really curios how this will turn out in the long run as you kind of give up some control (especially in terms of always getting an „equal“ Responder (e.g. as defined by a future OpenAPI support).

@khanlou I also had an idea in regards to the actual implementation of injecting PropertyWrappers with the requestContext. Currently, you use Mirror to iterate over the properties of the Responder which is quite expensive. Instead you could make all PropertyWrappers append themselves to an array that is stored in a static variable on initialisation. You would have to use a NIO.ThreadSpecificVariable for that.

Basically, when a request arrives, before instantiating the Responder, you habe to place an empty array ob the static ThreadSpecificVariable. Then you call the Responder-intializer-closure and all the PropertyWrappers append themselves to the array. You then store the array (containing a copy of all PropertyWrappers) , from the static variable, along with the actual instance of the Responder. Before evaluating the Responder, just where you currently use Mirror, you iterate over the array instead. All changes here are non-mutating, as the changes only affect the Inner storage (which is a reference type). This also means that changes are propagated to the actual Responder instance. After that you can evaluate the Responder as usual.

This way you wouldn‘t have to use runtime reflection at all.

**Comment by khanlou** [comment]
> You then store the array (containing a copy of all PropertyWrappers) , from the static variable, along with the actual instance of the Responder. Before evaluating the Responder, just where you currently use Mirror, you iterate over the array instead. All changes here are non-mutating, as the changes only affect the Inner storage (which is a reference type).

Wouldn't this result in property wrapper `update` methods getting called for responders that won't be responding? That doesn't seem good to me, since they could have side effects (like updating a session's `lastActive` field or something).

**Comment by theMomax** [comment]
With the current setup, yes. You would have to adapt `Route` so you can do the matching without instantiating the `Responder`. Basically, instead of storing closures of `Route`, each `Route` would have to store a closure of its `Responder`. Then you can directly access the `RouteMatcher` without initializing the `Responder`.

Starting from [that line](https://github.com/khanlou/Meridian/blob/37394c6255d0062090b59d6e4479cbd1af9c9236/Meridian/HTTPHandler.swift#L94), you'd then have about the following:

```swift
let results: (() -> Responder, MatchedRoute)?
(results, errorRenderer) = router.route(for: header)

guard let (routeClosure, matchedRoute) = results else {
    throw NoRouteFound()
}

let requestContext = RequestContext(
    header: header,
    matchedRoute: matchedRoute,
    postBody: body
)

var errors: [Error] = []

myStaticThreadSpecificVariable.currentValue.childrenArray = []

let route = routeClosure()

let children = myStaticThreadSpecificVariable.currentValue.childrenArray

for child in children {
    if let prop = child as? PropertyWrapper {
        prop.update(requestContext, errors: &errors)
    }
}

if let firstError = errors.first {
// from here it's just as before
```
